### PR TITLE
fix: build on non-Unix platforms

### PR DESCRIPTION
**Pull request by tdakkota**

### CODE REVIEW

**Review by 9seconds — APPROVED** [review]
Oh. How come. I've forgot about windows. Thanks a lot!

**Comment by 9seconds** [comment]
@tdakkota i'm not sure why GH Actions failed. Would you mind to rerun jobs?

**Comment by 9seconds** [comment]
@tdakkota ping?

**Comment by tdakkota** [comment]
`golangci-lint` workflow failed. `interfacer` linter suggested to pass `syscall.RawConn` instead of `*net.TCPConn`.

**Comment by ernado** [comment]
It's ok to disable interfacer linter in general, too much noise.

**Comment by 9seconds** [comment]
I tend to prefer a linter fascism, especially for contributions. In this certain case I'm fine with `// nolint: interfacer` here. I do not like to disable it globally because it is very useful for a code we own and maintain.

**Pull request closed without merging**
