### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Eternity-Yarr**
- little typo in docker command line 
- added more preferred 'secure only' example

### CODE REVIEW

**Comment by Eternity-Yarr** [comment]
I mean..
```
# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false

#  docker run --help | grep '\-q\b'
# 
```
What is `-q` ?

**Comment by Eternity-Yarr** [comment]
Is it `-p 127.0.0.1:3129:3129` ?

**Comment by 9seconds** [comment]
Thanks! Yep, the syntax is broken, `-q` is a flag of application, not docker :( I'll review that later.

**Comment by 9seconds** [comment]
Okay, seems if I merge this version, there would be much less confusion :) Thanks a lot!

**Pull request merged**
