### PR TITLE
V2

### PR DESCRIPTION
**Pull request by 9seconds**
So, a new project rewrite has been started. I'm really happy that this is a recent chance in my career when I can debloat something instead of bloating it up. I'm really happy and excited!

So, I'm going to have this WIP PR in a draft mode where you can see what is happening, comment or suggest. I'm going to make a progress and comment from time to time what is happening and what are current plans.

### CODE REVIEW

**Comment by 9seconds** [comment]
So, what do I have so far now:

1. Everything was removed and I've started from scratch
2. CI is working and for now it is fine to fail
3. I've made a couple of base structures and whole network package

So, the idea behind separate network package is that I wanna give users an ability to supply their own socks5 proxies. It means, that you can finally chain mtg with v2ray/gost/shadowsocks whatsoever. To be honest, I've even added a native integration with ShadowSocks but after some thinking, removed that. The reason is simple: we can't support all combinations of all anti-censorship software here. Just imagine: Trojan, VMess, ShadowSocks. Also, with SIP003, we also need to support obfuscation plugins and KCPTun.

For now, network can be:

1. Plain one
2. Socks5 proxy
3. Load balancing between socks5 proxies with circuit breakers
4. If DNS name should be resolved, it is done via DOH which is made via the same proxy (so, in theory no traffic has to be leaked)

Sorry, let's just have a SOCKS5 as a lingua franca of all proxy software :) If you wanna have a complex pipeline, you can use v2ray or gost.

Next plans are:

1. Make another iteration on configuration file.
2. Make `generate-secret` and `access` commands

**Comment by 9seconds** [comment]
We have 2 CLI commands now: `generate-secret` and `access`. So, this JSON file which was printed on proxy startup has been moved to a separate command.

**Comment by 9seconds** [comment]
So far, configuration file is "stabilised' (at least, I'm happy with its state). All code which processes a config is tested. The next goal is to test `access` and `generate-secret` CLI commands.

**Comment by 9seconds** [comment]
Commands are tested. Next step is to define logger (I gonna use zerolog), firehol and antireplay routines.

**Comment by 9seconds** [comment]
Logger, antireplay and firehol are landed. Next goal is to start to assemble proxy itself.

**Comment by 9seconds** [comment]
Implemented event stream. This is a concept when proxy issues a generic event and spit it into a stream. Stream has a list of observers which pick it up and do something. For example, we can use it for stats.

Next stop are stats observers. After that all pieces of puzzle are ready and I can concentrate on proxy itself.

**Comment by 9seconds** [comment]
Stats are done (both statsd and prometheus). So, all helper pieces are ready, now it is a time for a proxy itself.

**Comment by ernado** [comment]
Impressive work!
JFYI: We are using mtg in https://github.com/gotd/td for proxy testing, so embeddable version (i.e. proxy as a library, not as a binary) would be great

**Comment by 9seconds** [comment]
Client-side part of obfuscated2 is done. Next target is telegram connection + telegram side of obfuscated2. After that, the a shape of proxy has started to come: it will work with simple secrets/secure secrets. But please remember that I won't support this mode in production. Once it is done, I start to implement fake tls which will effectively be a single implementation.

**Comment by 9seconds** [comment]
Proxy is kinda working end-to-end now in a simple mode. Now I have to stabilize a new code with a test suite and implement fake tls.

**Comment by 9seconds** [comment]
Base faketls processing is done. mtg can accept, validate and establish a faketls connection (but cannot understand it yet). Now I need to do domain fronting + fake tls conn wrapper.

**Comment by 9seconds** [comment]
Important milestone: a proxy is fully functional now, domain fronting works, faketls works. You can use it now.

Next milestones before converting this draft into a real PR are:

- [ ] Testing of mtglib
- [ ] Testing of faketls
- [ ] New metrics: a number of replay attacks, number of domain fronting transmission, open connections to front domain and front domain traffic
- [ ] Stabilization of here and there
- [ ] Polishing things
- [ ] Documentation

**Comment by 9seconds** [comment]
I've switched my internal proxy I personally use to this guy. So i'm dogfooding now.

**Comment by 9seconds** [comment]
Okay, metrics are fully implemented and working fine

**Comment by 9seconds** [comment]
A progress so far: I've mostly been working on improving code coverage. Currently, we do have **80.74%** for the whole application.

I really want to be able to make a simple integration test: to connect to proxy and do ping to Telegram. But apparently it is really complex. I've been trying with https://github.com/Arman92/go-tdlib but tdlib is kinda insane: it does not work for me and I do not want to complexify a whole build process in such a way. I hope that https://github.com/gotd/td will solve it eventually. I do not have high hopes to https://github.com/xelaj/mtproto because it has animated GIFs in README.

All I need is:

1. Initialize a client
2. Give address of proxy + its secret to a client
3. Make a Ping call
4. Verify that Pong is received

**Comment by 9seconds** [comment]
Next stop is documentation. After that README file

**Comment by 9seconds** [comment]
Documentation is done. I need only to create a README file

**Pull request merged**
